Dodanie pamiętnika oraz zadań.
t0meck-pj/sop2021-22_23c pull request #12
Opened 2022-03-24 15:30 UTC by s24256-pj

Drugie zajęcia jeszcze niedokończone.

2022-03-27 00:25 UTC, t0meck-pj requested changes
Marto, sporo straciłaś. Bardzo mi przykro z tego powodu. Zapewne miałaś powód swojej nieobecności. Tu w tym momencie w to nie wnikam. Natomiast materiał powinnaś nadrobić. Są dostępne konsultacje w ramach których możemy jeszcze raz materiał z tych zajęć przerobić.

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/pamietnik.txt
> +3. Nie do końca zrozumiałam partycje i przydzielanie pamięci.
Jak chcesz możemy w ramach konsultacji wrócić do tego tematu.

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/pamietnik.txt
> +5. Dużo informacji do zapamiętania co gdzie i jak trzeba kliknąć i zmienić, bardzo żałuję, że robiłam to na komputerze uczelnianym. Teraz nie jestem pewna czy instalacja na moim koputerze dobrze prze
W ramach konsultacji możemy jeszcze raz przeprowadzić instalację na Twoim komputerze.

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/pamietnik.txt
> +Nie było mnie na zajęciach, ćwiczenia odrobiłam w domu. Niestety jeszcze nie wiem jak tworzyć skrypty, ale na pewno po przejrzeniu wykładów nadrobię dany materiał.
Treść wykładów i ćwiczeń nie pokrywa się w 100%

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/Zajecia1.txt
> +1.Pobieramy obraz systemu debian
Marto, proszę przeczytaj jeszcze raz "Wstęp" w pliku README.md a konkretnie pomiędzy słowem "Primo!" a tematem zajęć 1. Popraw proszę potem swój opis i wyślij do ponownej recenzji.

Lista, którą tu umieściłaś jest dobrym początkiem. Teraz większość punktów trzeba będzie rozbudować o dość duże opisy. Duże nie dlatego, że trzeba tam "lać wodę" lecz tematy w nich poruszane są obszerne i jako takich nie da się ich opisać jednym zdaniem.

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/Zajecia2.txt
> +export -n ZMIENNA
Biorę pod uwagę to, że wspomniałaś, że nie było Cię na zajęciach i zadania wykonujesz "na ślepo".
W materiałach jest drobny błąd.
export powoduje, że zmienna wraz z wartością jest dostępna w procesach potomnych procesu bash. Czyli mówiąc kolokwialnie w bashach uruchomionych w bashu.
export niejako ze zmiennej o zakresie lokalnym (w danym procesie bash) robi zmienną o charakterze dziedziczonym w dół dzięki czemu jest dostępnach w podprocesach.
export -n "ulokalnia" bądz "odexportowuje" ją ponownie czyniąc z niej zmienną niedziedziczoną.

unset zaś dopiero usuwa zmienną. Oddefiniowywuje ją.

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/Zajecia2.txt
> +PS1 - konsola wyświetla mi [1] 20741 następnie bash: PS1: nie znaleziono polecenia następnie informacje o zakończeniu echo, nie wiem co to oznacza, w internecie jest to zmienna znaku zachęty
A zobacz sobie coś takiego:
```
echo $PS1
export PS1='Nudze sie. Co mam zrobic? '
```
To pierwsze echo jest po to byś mogła powrócić do poprzedniej wartości gdy zrozumiesz co to robi.

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/Zajecia2.txt
> +ZM=$(ls -la) (wyświetla mi wszystko jednym ciągiem)
W obu przypadkach nie powinno wyświetlić nic.
No chyba, że masz na myśli, że po wywołaniu wypisujesz jeszcze wartość zmiennej ZM.

2022-03-27 00:25 UTC, t0meck-pj commented on s24256-MartaSzpilka/Zajecia2.txt
> +X-'ls -l'
Tu są użyte backtick-i czyli te takie skośne apostrofy. Przeważnie jest to przycisk na lewo od 1 nad przyciskiem TAB.

2022-03-27 00:27 UTC, t0meck-pj commented
1. Proszę o kontakt mailowy.
2. Aktualnie Twój opis jest zbyt ubogi. Bardzo trzeba go rozbudować miejscami.
Po uzupełnieniu opisu i poprawieniu zadań prosze wystaw kolejny PR.

2022-03-27 00:27 UTC, closed without merging

2022-03-28 21:04 UTC, s24256-pj commented
Dobry wieczór,

Dziękuję za odpowiedz. Bardzo chętnie umówiłabym się z Panem na
konsultacje, bo samej mi to troszkę ciężko zrozumieć - nawet z pomocą
internetu i dostępnych materiałów.
Czy termin jest ustalony z góry czy jest możliwość ustalenia go?

Pozdrawiam,
Marta Szpilka


On Sun, 27 Mar 2022 at 01:25, t0meck-pj ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Marto, sporo straciłaś. Bardzo mi przykro z tego powodu. Zapewne miałaś
> powód swojej nieobecności. Tu w tym momencie w to nie wnikam. Natomiast
> materiał powinnaś nadrobić. Są dostępne konsultacje w ramach których możemy
> jeszcze raz materiał z tych zajęć przerobić.
> ------------------------------
>
> In s24256-MartaSzpilka/pamietnik.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835826480>
> :
>
> > @@ -0,0 +1,19 @@
>
> +Pamiętnik SOP 2022
>
> +
>
> +1.Opis zajec
>
> +2.Czego sie nauczylas/es
>
> +3.Co jest dla Ciebie jeszcze nie jasne i musisz poglebic temat
>
> +4.Co bylo zaskakujacego
>
> +5.Twoje przemyslenia o calych zajeciach i zadaniach
>
> +
>
> +- 05.03.2022
>
> +
>
> +1. Na pierwszych zajęciach instalowaliśmy debiana na maszynie wirtualnej.
>
> +2. Instalować debiana.
>
> +3. Nie do końca zrozumiałam partycje i przydzielanie pamięci.
>
>
> Jak chcesz możemy w ramach konsultacji wrócić do tego tematu.
> ------------------------------
>
> In s24256-MartaSzpilka/pamietnik.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835826513>
> :
>
> > @@ -0,0 +1,19 @@
>
> +Pamiętnik SOP 2022
>
> +
>
> +1.Opis zajec
>
> +2.Czego sie nauczylas/es
>
> +3.Co jest dla Ciebie jeszcze nie jasne i musisz poglebic temat
>
> +4.Co bylo zaskakujacego
>
> +5.Twoje przemyslenia o calych zajeciach i zadaniach
>
> +
>
> +- 05.03.2022
>
> +
>
> +1. Na pierwszych zajęciach instalowaliśmy debiana na maszynie wirtualnej.
>
> +2. Instalować debiana.
>
> +3. Nie do końca zrozumiałam partycje i przydzielanie pamięci.
>
> +4. Ilość ustawień do zmiany podczas instalacji.
>
> +5. Dużo informacji do zapamiętania co gdzie i jak trzeba kliknąć i zmienić, bardzo żałuję, że robiłam to na komputerze uczelnianym. Teraz nie jestem pewna czy instalacja na moim koputerze dobrze przebiegła.
>
>
> W ramach konsultacji możemy jeszcze raz przeprowadzić instalację na Twoim
> komputerze.
> ------------------------------
>
> In s24256-MartaSzpilka/pamietnik.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835826548>
> :
>
> > +2.Czego sie nauczylas/es
>
> +3.Co jest dla Ciebie jeszcze nie jasne i musisz poglebic temat
>
> +4.Co bylo zaskakujacego
>
> +5.Twoje przemyslenia o calych zajeciach i zadaniach
>
> +
>
> +- 05.03.2022
>
> +
>
> +1. Na pierwszych zajęciach instalowaliśmy debiana na maszynie wirtualnej.
>
> +2. Instalować debiana.
>
> +3. Nie do końca zrozumiałam partycje i przydzielanie pamięci.
>
> +4. Ilość ustawień do zmiany podczas instalacji.
>
> +5. Dużo informacji do zapamiętania co gdzie i jak trzeba kliknąć i zmienić, bardzo żałuję, że robiłam to na komputerze uczelnianym. Teraz nie jestem pewna czy instalacja na moim koputerze dobrze przebiegła.
>
> +
>
> +- 19.03.2022
>
> +
>
> +Nie było mnie na zajęciach, ćwiczenia odrobiłam w domu. Niestety jeszcze nie wiem jak tworzyć skrypty, ale na pewno po przejrzeniu wykładów nadrobię dany materiał.
>
>
> Treść wykładów i ćwiczeń nie pokrywa się w 100%
> ------------------------------
>
> In s24256-MartaSzpilka/Zajecia1.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835826832>
> :
>
> > @@ -0,0 +1,12 @@
>
> +1.Pobieramy obraz systemu debian
>
>
> Marto, proszę przeczytaj jeszcze raz "Wstęp" w pliku README.md a
> konkretnie pomiędzy słowem "Primo!" a tematem zajęć 1. Popraw proszę potem
> swój opis i wyślij do ponownej recenzji.
>
> Lista, którą tu umieściłaś jest dobrym początkiem. Teraz większość punktów
> trzeba będzie rozbudować o dość duże opisy. Duże nie dlatego, że trzeba tam
> "lać wodę" lecz tematy w nich poruszane są obszerne i jako takich nie da
> się ich opisać jednym zdaniem.
> ------------------------------
>
> In s24256-MartaSzpilka/Zajecia2.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835827204>
> :
>
> > +Jeżeli dłuższe słowo to używamy "", ważne w przypadku używania innych zmiennych w tej zmiennej lub wartośći.
>
> +
>
> +W przypadku ciągu bez innych zmiennych lub wartości oraz bez (') możemy używać również ('').
>
> +
>
> +b)Zmienna środowiskowa (widoczna w podpowłokach i programach wykonawanych w danej powłoce) tworzenie:
>
> +
>
> +export ZMIENNA=wartość
>
> +
>
> +lub
>
> +
>
> +ZMIENNA=wartosc
>
> +export ZMIENNA
>
> +
>
> +c) Usuwanie takich zmiennych:
>
> +
>
> +export -n ZMIENNA
>
>
> Biorę pod uwagę to, że wspomniałaś, że nie było Cię na zajęciach i zadania
> wykonujesz "na ślepo".
> W materiałach jest drobny błąd.
> export powoduje, że zmienna wraz z wartością jest dostępna w procesach
> potomnych procesu bash. Czyli mówiąc kolokwialnie w bashach uruchomionych w
> bashu.
> export niejako ze zmiennej o zakresie lokalnym (w danym procesie bash)
> robi zmienną o charakterze dziedziczonym w dół dzięki czemu jest dostępnach
> w podprocesach.
> export -n "ulokalnia" bądz "odexportowuje" ją ponownie czyniąc z niej
> zmienną niedziedziczoną.
>
> unset zaś dopiero usuwa zmienną. Oddefiniowywuje ją.
> ------------------------------
>
> In s24256-MartaSzpilka/Zajecia2.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835827399>
> :
>
> > +
>
> +TU SPRAWDZĘ PO WPISANIU SKRYPTU:
>
> +$* -
>
> +$@ -
>
> +$0 -
>
> +$1 -
>
> +$2 -
>
> +$# -
>
> +$? -
>
> +$$ -
>
> +$! -
>
> +
>
> +b) PATH - zmienna wskazuję na jakąś lokalizacje pliku (jakaś ścieżka?)
>
> +RANDOM - losowa liczba wygenerowana przez bash
>
> +PWD - zmienna pokazująca naszą teraźniejszą lokalizacje działa tak samo jak komenda pwd
>
> +PS1 - konsola wyświetla mi [1] 20741 następnie bash: PS1: nie znaleziono polecenia następnie informacje o zakończeniu echo, nie wiem co to oznacza, w internecie jest to zmienna znaku zachęty
>
>
> A zobacz sobie coś takiego:
>
> echo $PS1
>
> export PS1='Nudze sie. Co mam zrobic? '
>
>
> To pierwsze echo jest po to byś mogła powrócić do poprzedniej wartości gdy
> zrozumiesz co to robi.
> ------------------------------
>
> In s24256-MartaSzpilka/Zajecia2.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835827461>
> :
>
> > +$2 -
>
> +$# -
>
> +$? -
>
> +$$ -
>
> +$! -
>
> +
>
> +b) PATH - zmienna wskazuję na jakąś lokalizacje pliku (jakaś ścieżka?)
>
> +RANDOM - losowa liczba wygenerowana przez bash
>
> +PWD - zmienna pokazująca naszą teraźniejszą lokalizacje działa tak samo jak komenda pwd
>
> +PS1 - konsola wyświetla mi [1] 20741 następnie bash: PS1: nie znaleziono polecenia następnie informacje o zakończeniu echo, nie wiem co to oznacza, w internecie jest to zmienna znaku zachęty
>
> +USER - wyświetla nazwe użytkownika w tym przypadku mój numer indeksu
>
> +HOSTNAME - wyświetla nazwe hosta (szuflandia)
>
> +OSTYPE - wyświetla nazwe systemu operacyjnego, na którym pracujemy (linux-gnu)
>
> +
>
> +c)
>
> +ZM=$(ls -la) (wyświetla mi wszystko jednym ciągiem)
>
>
> W obu przypadkach nie powinno wyświetlić nic.
> No chyba, że masz na myśli, że po wywołaniu wypisujesz jeszcze wartość
> zmiennej ZM.
> ------------------------------
>
> In s24256-MartaSzpilka/Zajecia2.txt
> <https://github.com/t0meck-pj/sop2021-22_23c/pull/12#discussion_r835827537>
> :
>
> > +b) PATH - zmienna wskazuję na jakąś lokalizacje pliku (jakaś ścieżka?)
>
> +RANDOM - losowa liczba wygenerowana przez bash
>
> +PWD - zmienna pokazująca naszą teraźniejszą lokalizacje działa tak samo jak komenda pwd
>
> +PS1 - konsola wyświetla mi [1] 20741 następnie bash: PS1: nie znaleziono polecenia następnie informacje o zakończeniu echo, nie wiem co to oznacza, w internecie jest to zmienna znaku zachęty
>
> +USER - wyświetla nazwe użytkownika w tym przypadku mój numer indeksu
>
> +HOSTNAME - wyświetla nazwe hosta (szuflandi [...]